{
//=========Macro generated from canvas: QCDEstimation/QCDEstimation
//=========  (Sun Mar  8 15:06:21 2015) by ROOT version5.34/03
   TCanvas *QCDEstimation = new TCanvas("QCDEstimation", "QCDEstimation",405,83,700,502);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   QCDEstimation->Range(0,0,1,1);
   QCDEstimation->SetFillColor(0);
   QCDEstimation->SetBorderMode(0);
   QCDEstimation->SetBorderSize(2);
   QCDEstimation->SetLeftMargin(0.18);
   QCDEstimation->SetRightMargin(0.08);
   QCDEstimation->SetTopMargin(0.07);
   QCDEstimation->SetBottomMargin(0.17);
   QCDEstimation->SetFrameLineWidth(3);
   QCDEstimation->SetFrameBorderMode(0);
   QCDEstimation->SetFrameBorderSize(0);
  
// ------------>Primitives in pad: QCDEstimation_1
   TPad *QCDEstimation_1 = new TPad("QCDEstimation_1", "QCDEstimation_1",0.01,0.01,0.99,0.99);
   QCDEstimation_1->Draw();
   QCDEstimation_1->cd();
   QCDEstimation_1->Range(63.51351,0.1349436,266.2162,0.8293808);
   QCDEstimation_1->SetFillColor(0);
   QCDEstimation_1->SetBorderMode(0);
   QCDEstimation_1->SetBorderSize(2);
   QCDEstimation_1->SetLeftMargin(0.18);
   QCDEstimation_1->SetRightMargin(0.08);
   QCDEstimation_1->SetTopMargin(0.07);
   QCDEstimation_1->SetBottomMargin(0.17);
   QCDEstimation_1->SetFrameLineWidth(3);
   QCDEstimation_1->SetFrameBorderMode(0);
   QCDEstimation_1->SetFrameBorderSize(0);
   QCDEstimation_1->SetFrameLineWidth(3);
   QCDEstimation_1->SetFrameBorderMode(0);
   QCDEstimation_1->SetFrameBorderSize(0);
   Double_t xAxis1[5] = {100, 125, 150, 200, 250}; 
   
   TH1D *hQCDinregionC1 = new TH1D("hQCDinregionC1","hQCDinregionC1",4, xAxis1);
   hQCDinregionC1->SetBinContent(1,0.5374131);
   hQCDinregionC1->SetBinContent(2,0.4934805);
   hQCDinregionC1->SetBinContent(3,0.3793057);
   hQCDinregionC1->SetBinContent(4,0.3769862);
   hQCDinregionC1->SetBinContent(5,1.101324);
   hQCDinregionC1->SetBinError(1,0.2182251);
   hQCDinregionC1->SetBinError(2,0.07913925);
   hQCDinregionC1->SetBinError(3,0.04474248);
   hQCDinregionC1->SetBinError(4,0.1000529);
   hQCDinregionC1->SetBinError(5,0.3900053);
   hQCDinregionC1->SetEntries(48.46955);
   
   TF1 *func = new TF1("func","pol0",100,250);
   func->SetFillColor(19);
   func->SetFillStyle(0);
   func->SetLineColor(2);
   func->SetLineWidth(5);
   func->SetChisquare(2.024276);
   func->SetNDF(3);
   func->GetXaxis()->SetNdivisions(505);
   func->GetXaxis()->SetLabelFont(42);
   func->GetXaxis()->SetLabelSize(0.07);
   func->GetXaxis()->SetTitleSize(0.07);
   func->GetXaxis()->SetTitleOffset(1.1);
   func->GetXaxis()->SetTitleFont(42);
   func->GetYaxis()->SetNdivisions(505);
   func->GetYaxis()->SetLabelFont(42);
   func->GetYaxis()->SetLabelSize(0.07);
   func->GetYaxis()->SetTitleSize(0.07);
   func->GetYaxis()->SetTitleOffset(1.3);
   func->GetYaxis()->SetTitleFont(42);
   func->SetParameter(0,0.4066338);
   func->SetParError(0,0.03580372);
   func->SetParLimits(0,0,0);
   hQCDinregionC1->GetListOfFunctions()->Add(func);
   
   TPaveStats *ptstats = new TPaveStats(0.5058644,0.8069872,0.782958,0.8588724,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(0);
   ptstats->SetFillColor(0);
   ptstats->SetLineColor(0);
   ptstats->SetLineWidth(2);
   ptstats->SetTextAlign(12);
   ptstats->SetTextColor(0);
   TText *text = ptstats->AddText("p0       = 0.4066 #pm 0.0358 ");
   text->SetTextSize(0.04773435);
   ptstats->SetOptStat(0);
   ptstats->SetOptFit(73);
   ptstats->Draw();
   hQCDinregionC1->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(hQCDinregionC1);
   hQCDinregionC1->SetLineWidth(5);
   hQCDinregionC1->GetXaxis()->SetTitle("#Sigma m_{T}^{#tau_{i}}");
   hQCDinregionC1->GetXaxis()->SetNdivisions(505);
   hQCDinregionC1->GetXaxis()->SetLabelFont(42);
   hQCDinregionC1->GetXaxis()->SetLabelSize(0.07);
   hQCDinregionC1->GetXaxis()->SetTitleSize(0.07);
   hQCDinregionC1->GetXaxis()->SetTitleOffset(1.1);
   hQCDinregionC1->GetXaxis()->SetTitleFont(42);
   hQCDinregionC1->GetYaxis()->SetTitle("Transfer factor(C/B)");
   hQCDinregionC1->GetYaxis()->SetNdivisions(505);
   hQCDinregionC1->GetYaxis()->SetLabelFont(42);
   hQCDinregionC1->GetYaxis()->SetLabelSize(0.07);
   hQCDinregionC1->GetYaxis()->SetTitleSize(0.07);
   hQCDinregionC1->GetYaxis()->SetTitleOffset(1.1);
   hQCDinregionC1->GetYaxis()->SetTitleFont(42);
   hQCDinregionC1->GetZaxis()->SetLabelFont(42);
   hQCDinregionC1->GetZaxis()->SetLabelSize(0.035);
   hQCDinregionC1->GetZaxis()->SetTitleSize(0.035);
   hQCDinregionC1->GetZaxis()->SetTitleFont(42);
   hQCDinregionC1->Draw("");
   QCDEstimation_1->Modified();
   QCDEstimation->cd();
   QCDEstimation->Modified();
   QCDEstimation->cd();
   QCDEstimation->SetSelected(QCDEstimation);
}
