void MT2_tauMTgt200_DDFakeEleTau(){
//=========Macro generated from canvas: muTau_log_comp_overlayc_ratio/
//=========  (Sun Oct 11 19:26:45 2015) by ROOT version5.34/19
   TCanvas *muTau_log_comp_overlayc_ratio = new TCanvas("MT2_tauMTgt200_DDFakeEleTau", "",1,52,600,600);
   gStyle->SetOptFit(1);
   muTau_log_comp_overlayc_ratio->Range(0,0,1,1);
   muTau_log_comp_overlayc_ratio->SetFillColor(0);
   muTau_log_comp_overlayc_ratio->SetBorderMode(0);
   muTau_log_comp_overlayc_ratio->SetBorderSize(2);
   muTau_log_comp_overlayc_ratio->SetLeftMargin(0.13);
   muTau_log_comp_overlayc_ratio->SetRightMargin(0.08);
   muTau_log_comp_overlayc_ratio->SetTopMargin(0.07);
   muTau_log_comp_overlayc_ratio->SetBottomMargin(0.13);
   muTau_log_comp_overlayc_ratio->SetFrameBorderMode(0);
   muTau_log_comp_overlayc_ratio->SetFrameBorderSize(0);

   muTau_log_comp_overlayc_ratio->SetLogy();
  
// ------------>Primitives in pad: muTau_log_comp_overlay_plotpad
   // TPad *muTau_log_comp_overlay_plotpad = new TPad("muTau_log_comp_overlay_plotpad", "Pad containing the overlay plot",0,0.211838,1,1);
   // muTau_log_comp_overlay_plotpad->Draw();
   // muTau_log_comp_overlay_plotpad->cd();
   // muTau_log_comp_overlay_plotpad->Range(26.64886,-2.48782,128.1175,2.364311);
   // muTau_log_comp_overlay_plotpad->SetFillColor(0);
   // muTau_log_comp_overlay_plotpad->SetFillStyle(4000);
   // muTau_log_comp_overlay_plotpad->SetBorderMode(0);
   // muTau_log_comp_overlay_plotpad->SetBorderSize(2);
   // muTau_log_comp_overlay_plotpad->SetLogy();
   // muTau_log_comp_overlay_plotpad->SetLeftMargin(0.131579);
   // muTau_log_comp_overlay_plotpad->SetRightMargin(0.08);
   // muTau_log_comp_overlay_plotpad->SetTopMargin(0.06895515);
   // muTau_log_comp_overlay_plotpad->SetBottomMargin(0.07206074);
   // muTau_log_comp_overlay_plotpad->SetFrameLineWidth(3);
   // muTau_log_comp_overlay_plotpad->SetFrameBorderMode(0);
   // muTau_log_comp_overlay_plotpad->SetFrameBorderSize(0);
   // muTau_log_comp_overlay_plotpad->SetFrameLineWidth(3);
   // muTau_log_comp_overlay_plotpad->SetFrameBorderMode(0);
   // muTau_log_comp_overlay_plotpad->SetFrameBorderSize(0);
   
   THStack *h_stack = new THStack();
   h_stack->SetName("h_stack");
   h_stack->SetTitle("");
   h_stack->SetMinimum(0.1);
   h_stack->SetMaximum(200.00391);
   
   TH1F *h_stack_stack_1_stack_1 = new TH1F("h_stack_stack_1_stack_1","",120,0,120);
   h_stack_stack_1_stack_1->SetMinimum(0.1);
   h_stack_stack_1_stack_1->SetMaximum(200.0);
   h_stack_stack_1_stack_1->SetDirectory(0);
   h_stack_stack_1_stack_1->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   h_stack_stack_1_stack_1->SetLineColor(ci);
   h_stack_stack_1_stack_1->SetLineWidth(2);
   h_stack_stack_1_stack_1->GetXaxis()->SetTitle("M_{T2}");
   h_stack_stack_1_stack_1->GetXaxis()->SetRange(41,120);
   h_stack_stack_1_stack_1->GetXaxis()->SetNdivisions(505);
   h_stack_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   h_stack_stack_1_stack_1->GetXaxis()->SetLabelSize(0.05);
   h_stack_stack_1_stack_1->GetXaxis()->SetTitleSize(0.05);
   h_stack_stack_1_stack_1->GetXaxis()->SetTitleOffset(1.1);
   h_stack_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   h_stack_stack_1_stack_1->GetYaxis()->SetTitle("Events");
   h_stack_stack_1_stack_1->GetYaxis()->SetNdivisions(505);
   h_stack_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   h_stack_stack_1_stack_1->GetYaxis()->SetLabelSize(0.05);
   h_stack_stack_1_stack_1->GetYaxis()->SetTitleSize(0.05);
   h_stack_stack_1_stack_1->GetYaxis()->SetTitleOffset(1.3);
   h_stack_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   h_stack_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   h_stack_stack_1_stack_1->GetZaxis()->SetLabelSize(0.035);
   h_stack_stack_1_stack_1->GetZaxis()->SetTitleSize(0.035);
   h_stack_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   h_stack->SetHistogram(h_stack_stack_1_stack_1);
   
   Double_t xAxis1[5] = {40, 50, 70, 90, 120}; 
   
   TH1D *TauMTCut_MT2_ZX_Rebinned = new TH1D("TauMTCut_MT2_ZX_Rebinned","",4, xAxis1);
   TauMTCut_MT2_ZX_Rebinned->SetBinContent(0,-0.0009098457);
   TauMTCut_MT2_ZX_Rebinned->SetBinContent(1,0.08118604);
   TauMTCut_MT2_ZX_Rebinned->SetBinContent(2,0.1725647);
   TauMTCut_MT2_ZX_Rebinned->SetBinContent(3,0.05245734);
   TauMTCut_MT2_ZX_Rebinned->SetBinContent(4,0.1922269);
   TauMTCut_MT2_ZX_Rebinned->SetBinContent(5,0.06469722);
   TauMTCut_MT2_ZX_Rebinned->SetBinError(0,0.001234334);
   TauMTCut_MT2_ZX_Rebinned->SetBinError(1,0.03398382);
   TauMTCut_MT2_ZX_Rebinned->SetBinError(2,0.05977127);
   TauMTCut_MT2_ZX_Rebinned->SetBinError(3,0.02650494);
   TauMTCut_MT2_ZX_Rebinned->SetBinError(4,0.09825628);
   TauMTCut_MT2_ZX_Rebinned->SetBinError(5,0.07843811);
   TauMTCut_MT2_ZX_Rebinned->SetEntries(24.05063);
   TauMTCut_MT2_ZX_Rebinned->SetStats(0);

   ci = TColor::GetColor("#006600");
   TauMTCut_MT2_ZX_Rebinned->SetFillColor(ci);

   ci = TColor::GetColor("#006600");
   TauMTCut_MT2_ZX_Rebinned->SetLineColor(ci);
   TauMTCut_MT2_ZX_Rebinned->SetLineWidth(2);

   ci = TColor::GetColor("#006600");
   TauMTCut_MT2_ZX_Rebinned->SetMarkerColor(ci);
   TauMTCut_MT2_ZX_Rebinned->GetXaxis()->SetRange(1,11);
   TauMTCut_MT2_ZX_Rebinned->GetXaxis()->SetNdivisions(505);
   TauMTCut_MT2_ZX_Rebinned->GetXaxis()->SetLabelFont(42);
   TauMTCut_MT2_ZX_Rebinned->GetXaxis()->SetLabelSize(0.07);
   TauMTCut_MT2_ZX_Rebinned->GetXaxis()->SetTitleSize(0.07);
   TauMTCut_MT2_ZX_Rebinned->GetXaxis()->SetTitleOffset(1.1);
   TauMTCut_MT2_ZX_Rebinned->GetXaxis()->SetTitleFont(42);
   TauMTCut_MT2_ZX_Rebinned->GetYaxis()->SetNdivisions(505);
   TauMTCut_MT2_ZX_Rebinned->GetYaxis()->SetLabelFont(42);
   TauMTCut_MT2_ZX_Rebinned->GetYaxis()->SetLabelSize(0.07);
   TauMTCut_MT2_ZX_Rebinned->GetYaxis()->SetTitleSize(0.07);
   TauMTCut_MT2_ZX_Rebinned->GetYaxis()->SetTitleOffset(1.3);
   TauMTCut_MT2_ZX_Rebinned->GetYaxis()->SetTitleFont(42);
   TauMTCut_MT2_ZX_Rebinned->GetZaxis()->SetLabelFont(42);
   TauMTCut_MT2_ZX_Rebinned->GetZaxis()->SetLabelSize(0.035);
   TauMTCut_MT2_ZX_Rebinned->GetZaxis()->SetTitleSize(0.035);
   TauMTCut_MT2_ZX_Rebinned->GetZaxis()->SetTitleFont(42);

   Double_t xAxis2[5] = {40, 50, 70, 90, 120}; 
   
   TH1D *TauMTCut_MT2_Top_Rebinned = new TH1D("TauMTCut_MT2_Top_Rebinned","",4, xAxis2);
   TauMTCut_MT2_Top_Rebinned->SetBinContent(0,-0.2165999);
   TauMTCut_MT2_Top_Rebinned->SetBinContent(1,0.8233909);
   TauMTCut_MT2_Top_Rebinned->SetBinContent(2,1.455251);
   TauMTCut_MT2_Top_Rebinned->SetBinContent(3,1.253021);
   TauMTCut_MT2_Top_Rebinned->SetBinContent(4,0.01808909);
   TauMTCut_MT2_Top_Rebinned->SetBinContent(5,0.01808909);
   TauMTCut_MT2_Top_Rebinned->SetBinError(0,0.3044367);
   TauMTCut_MT2_Top_Rebinned->SetBinError(1,0.9159425);
   TauMTCut_MT2_Top_Rebinned->SetBinError(2,2.030144);
   TauMTCut_MT2_Top_Rebinned->SetBinError(3,1.088864);
   TauMTCut_MT2_Top_Rebinned->SetBinError(4,0.02022422);
   TauMTCut_MT2_Top_Rebinned->SetBinError(5,0.01808909);
   TauMTCut_MT2_Top_Rebinned->SetEntries(2.492757);
   TauMTCut_MT2_Top_Rebinned->SetStats(0);

   ci = TColor::GetColor("#3366cc");
   TauMTCut_MT2_Top_Rebinned->SetFillColor(ci);

   ci = TColor::GetColor("#3366cc");
   TauMTCut_MT2_Top_Rebinned->SetLineColor(ci);
   TauMTCut_MT2_Top_Rebinned->SetLineWidth(2);

   ci = TColor::GetColor("#3366cc");
   TauMTCut_MT2_Top_Rebinned->SetMarkerColor(ci);
   TauMTCut_MT2_Top_Rebinned->GetXaxis()->SetRange(1,11);
   TauMTCut_MT2_Top_Rebinned->GetXaxis()->SetNdivisions(505);
   TauMTCut_MT2_Top_Rebinned->GetXaxis()->SetLabelFont(42);
   TauMTCut_MT2_Top_Rebinned->GetXaxis()->SetLabelSize(0.07);
   TauMTCut_MT2_Top_Rebinned->GetXaxis()->SetTitleSize(0.07);
   TauMTCut_MT2_Top_Rebinned->GetXaxis()->SetTitleOffset(1.1);
   TauMTCut_MT2_Top_Rebinned->GetXaxis()->SetTitleFont(42);
   TauMTCut_MT2_Top_Rebinned->GetYaxis()->SetNdivisions(505);
   TauMTCut_MT2_Top_Rebinned->GetYaxis()->SetLabelFont(42);
   TauMTCut_MT2_Top_Rebinned->GetYaxis()->SetLabelSize(0.07);
   TauMTCut_MT2_Top_Rebinned->GetYaxis()->SetTitleSize(0.07);
   TauMTCut_MT2_Top_Rebinned->GetYaxis()->SetTitleOffset(1.3);
   TauMTCut_MT2_Top_Rebinned->GetYaxis()->SetTitleFont(42);
   TauMTCut_MT2_Top_Rebinned->GetZaxis()->SetLabelFont(42);
   TauMTCut_MT2_Top_Rebinned->GetZaxis()->SetLabelSize(0.035);
   TauMTCut_MT2_Top_Rebinned->GetZaxis()->SetTitleSize(0.035);
   TauMTCut_MT2_Top_Rebinned->GetZaxis()->SetTitleFont(42);
   Double_t xAxis3[5] = {40, 50, 70, 90, 120}; 
   
   TH1D *TauMTCut_MT2_WW_Rebinned = new TH1D("TauMTCut_MT2_WW_Rebinned","",4, xAxis3);
   TauMTCut_MT2_WW_Rebinned->SetBinContent(0,-0.250828);
   TauMTCut_MT2_WW_Rebinned->SetBinContent(1,0.2455386);
   TauMTCut_MT2_WW_Rebinned->SetBinContent(2,1.317099);
   TauMTCut_MT2_WW_Rebinned->SetBinContent(3,0.2583779);
   TauMTCut_MT2_WW_Rebinned->SetBinContent(4,0.02707293);
   TauMTCut_MT2_WW_Rebinned->SetBinContent(5,-0.02362514);
   TauMTCut_MT2_WW_Rebinned->SetBinError(0,0.1512884);
   TauMTCut_MT2_WW_Rebinned->SetBinError(1,0.2004461);
   TauMTCut_MT2_WW_Rebinned->SetBinError(2,0.7086538);
   TauMTCut_MT2_WW_Rebinned->SetBinError(3,0.1938725);
   TauMTCut_MT2_WW_Rebinned->SetBinError(4,0.04508297);
   TauMTCut_MT2_WW_Rebinned->SetBinError(5,0.02362514);
   TauMTCut_MT2_WW_Rebinned->SetEntries(29.35356);
   TauMTCut_MT2_WW_Rebinned->SetStats(0);

   ci = TColor::GetColor("#000066");
   TauMTCut_MT2_WW_Rebinned->SetFillColor(ci);

   ci = TColor::GetColor("#000066");
   TauMTCut_MT2_WW_Rebinned->SetLineColor(ci);
   TauMTCut_MT2_WW_Rebinned->SetLineWidth(2);

   ci = TColor::GetColor("#000066");
   TauMTCut_MT2_WW_Rebinned->SetMarkerColor(ci);
   TauMTCut_MT2_WW_Rebinned->GetXaxis()->SetRange(1,11);
   TauMTCut_MT2_WW_Rebinned->GetXaxis()->SetNdivisions(505);
   TauMTCut_MT2_WW_Rebinned->GetXaxis()->SetLabelFont(42);
   TauMTCut_MT2_WW_Rebinned->GetXaxis()->SetLabelSize(0.07);
   TauMTCut_MT2_WW_Rebinned->GetXaxis()->SetTitleSize(0.07);
   TauMTCut_MT2_WW_Rebinned->GetXaxis()->SetTitleOffset(1.1);
   TauMTCut_MT2_WW_Rebinned->GetXaxis()->SetTitleFont(42);
   TauMTCut_MT2_WW_Rebinned->GetYaxis()->SetNdivisions(505);
   TauMTCut_MT2_WW_Rebinned->GetYaxis()->SetLabelFont(42);
   TauMTCut_MT2_WW_Rebinned->GetYaxis()->SetLabelSize(0.07);
   TauMTCut_MT2_WW_Rebinned->GetYaxis()->SetTitleSize(0.07);
   TauMTCut_MT2_WW_Rebinned->GetYaxis()->SetTitleOffset(1.3);
   TauMTCut_MT2_WW_Rebinned->GetYaxis()->SetTitleFont(42);
   TauMTCut_MT2_WW_Rebinned->GetZaxis()->SetLabelFont(42);
   TauMTCut_MT2_WW_Rebinned->GetZaxis()->SetLabelSize(0.035);
   TauMTCut_MT2_WW_Rebinned->GetZaxis()->SetTitleSize(0.035);
   TauMTCut_MT2_WW_Rebinned->GetZaxis()->SetTitleFont(42);
   Double_t xAxis4[5] = {40, 50, 70, 90, 120}; 
   
   TH1D *TauMTCut_MT2_Higgs_Rebinned = new TH1D("TauMTCut_MT2_Higgs_Rebinned","",4, xAxis4);
   TauMTCut_MT2_Higgs_Rebinned->SetBinContent(0,-0.07679207);
   TauMTCut_MT2_Higgs_Rebinned->SetBinContent(1,0.005385817);
   TauMTCut_MT2_Higgs_Rebinned->SetBinContent(2,9.458594e-11);
   TauMTCut_MT2_Higgs_Rebinned->SetBinContent(3,-1.07614e-10);
   TauMTCut_MT2_Higgs_Rebinned->SetBinContent(4,-0.01188814);
   TauMTCut_MT2_Higgs_Rebinned->SetBinContent(5,-0.0457448);
   TauMTCut_MT2_Higgs_Rebinned->SetBinError(0,0.04268872);
   TauMTCut_MT2_Higgs_Rebinned->SetBinError(1,0.01874256);
   TauMTCut_MT2_Higgs_Rebinned->SetBinError(2,0.02388197);
   TauMTCut_MT2_Higgs_Rebinned->SetBinError(3,0.01349562);
   TauMTCut_MT2_Higgs_Rebinned->SetBinError(4,0.02917367);
   TauMTCut_MT2_Higgs_Rebinned->SetBinError(5,0.02513);
   TauMTCut_MT2_Higgs_Rebinned->SetEntries(0.006502324);
   TauMTCut_MT2_Higgs_Rebinned->SetStats(0);
   TauMTCut_MT2_Higgs_Rebinned->SetFillColor(2);
   TauMTCut_MT2_Higgs_Rebinned->SetLineColor(2);
   TauMTCut_MT2_Higgs_Rebinned->SetLineWidth(2);
   TauMTCut_MT2_Higgs_Rebinned->SetMarkerColor(2);
   TauMTCut_MT2_Higgs_Rebinned->GetXaxis()->SetRange(1,11);
   TauMTCut_MT2_Higgs_Rebinned->GetXaxis()->SetNdivisions(505);
   TauMTCut_MT2_Higgs_Rebinned->GetXaxis()->SetLabelFont(42);
   TauMTCut_MT2_Higgs_Rebinned->GetXaxis()->SetLabelSize(0.07);
   TauMTCut_MT2_Higgs_Rebinned->GetXaxis()->SetTitleSize(0.07);
   TauMTCut_MT2_Higgs_Rebinned->GetXaxis()->SetTitleOffset(1.1);
   TauMTCut_MT2_Higgs_Rebinned->GetXaxis()->SetTitleFont(42);
   TauMTCut_MT2_Higgs_Rebinned->GetYaxis()->SetNdivisions(505);
   TauMTCut_MT2_Higgs_Rebinned->GetYaxis()->SetLabelFont(42);
   TauMTCut_MT2_Higgs_Rebinned->GetYaxis()->SetLabelSize(0.07);
   TauMTCut_MT2_Higgs_Rebinned->GetYaxis()->SetTitleSize(0.07);
   TauMTCut_MT2_Higgs_Rebinned->GetYaxis()->SetTitleOffset(1.3);
   TauMTCut_MT2_Higgs_Rebinned->GetYaxis()->SetTitleFont(42);
   TauMTCut_MT2_Higgs_Rebinned->GetZaxis()->SetLabelFont(42);
   TauMTCut_MT2_Higgs_Rebinned->GetZaxis()->SetLabelSize(0.035);
   TauMTCut_MT2_Higgs_Rebinned->GetZaxis()->SetTitleSize(0.035);
   TauMTCut_MT2_Higgs_Rebinned->GetZaxis()->SetTitleFont(42);
   Double_t xAxis5[5] = {40, 50, 70, 90, 120}; 
   
   TH1D *Total200_fromMuTau_MT2_data_Rebinned = new TH1D("Total200_fromMuTau_MT2_data_Rebinned","",4, xAxis5);
   Total200_fromMuTau_MT2_data_Rebinned->SetBinContent(0,40.97312);
   Total200_fromMuTau_MT2_data_Rebinned->SetBinContent(1,2.596472);
   Total200_fromMuTau_MT2_data_Rebinned->SetBinContent(2,28.54152);
   Total200_fromMuTau_MT2_data_Rebinned->SetBinContent(3,8.359853);
   Total200_fromMuTau_MT2_data_Rebinned->SetBinContent(4,2.734164);
   Total200_fromMuTau_MT2_data_Rebinned->SetBinContent(5,2.734164);
   Total200_fromMuTau_MT2_data_Rebinned->SetBinError(0,13.16947);
   Total200_fromMuTau_MT2_data_Rebinned->SetBinError(1,3.704278);
   Total200_fromMuTau_MT2_data_Rebinned->SetBinError(2,8.572413);
   Total200_fromMuTau_MT2_data_Rebinned->SetBinError(3,5.100058);
   Total200_fromMuTau_MT2_data_Rebinned->SetBinError(4,2.775038);
   Total200_fromMuTau_MT2_data_Rebinned->SetBinError(5,2.775038);
   Total200_fromMuTau_MT2_data_Rebinned->SetEntries(195);
   Total200_fromMuTau_MT2_data_Rebinned->SetStats(0);

   ci = TColor::GetColor("#cccc00");
   Total200_fromMuTau_MT2_data_Rebinned->SetFillColor(417);

   ci = TColor::GetColor("#cccc00");
   Total200_fromMuTau_MT2_data_Rebinned->SetLineColor(417);
   Total200_fromMuTau_MT2_data_Rebinned->SetLineWidth(2);

   ci = TColor::GetColor("#cccc00");
   Total200_fromMuTau_MT2_data_Rebinned->SetMarkerColor(ci);
   Total200_fromMuTau_MT2_data_Rebinned->GetXaxis()->SetRange(1,5);
   Total200_fromMuTau_MT2_data_Rebinned->GetXaxis()->SetNdivisions(505);
   Total200_fromMuTau_MT2_data_Rebinned->GetXaxis()->SetLabelFont(42);
   Total200_fromMuTau_MT2_data_Rebinned->GetXaxis()->SetLabelSize(0.07);
   Total200_fromMuTau_MT2_data_Rebinned->GetXaxis()->SetTitleSize(0.07);
   Total200_fromMuTau_MT2_data_Rebinned->GetXaxis()->SetTitleOffset(1.1);
   Total200_fromMuTau_MT2_data_Rebinned->GetXaxis()->SetTitleFont(42);
   Total200_fromMuTau_MT2_data_Rebinned->GetYaxis()->SetNdivisions(505);
   Total200_fromMuTau_MT2_data_Rebinned->GetYaxis()->SetLabelFont(42);
   Total200_fromMuTau_MT2_data_Rebinned->GetYaxis()->SetLabelSize(0.07);
   Total200_fromMuTau_MT2_data_Rebinned->GetYaxis()->SetTitleSize(0.07);
   Total200_fromMuTau_MT2_data_Rebinned->GetYaxis()->SetTitleOffset(1.3);
   Total200_fromMuTau_MT2_data_Rebinned->GetYaxis()->SetTitleFont(42);
   Total200_fromMuTau_MT2_data_Rebinned->GetZaxis()->SetLabelFont(42);
   Total200_fromMuTau_MT2_data_Rebinned->GetZaxis()->SetLabelSize(0.035);
   Total200_fromMuTau_MT2_data_Rebinned->GetZaxis()->SetTitleSize(0.035);
   Total200_fromMuTau_MT2_data_Rebinned->GetZaxis()->SetTitleFont(42);


   h_stack->Add(TauMTCut_MT2_Higgs_Rebinned,"");
   h_stack->Add(TauMTCut_MT2_WW_Rebinned,"");
   h_stack->Add(TauMTCut_MT2_Top_Rebinned,"");
   h_stack->Add(TauMTCut_MT2_ZX_Rebinned,"");
   h_stack->Add(Total200_fromMuTau_MT2_data_Rebinned,"");
   h_stack->Draw("hist");

   Double_t xAxis8[5] = {40, 50, 70, 90, 120}; 
   TH1D *h__MC = new TH1D("h__MC","",4, xAxis8);
   h__MC->Add(TauMTCut_MT2_ZX_Rebinned);		 
   h__MC->Add(TauMTCut_MT2_Top_Rebinned);		 
   h__MC->Add(TauMTCut_MT2_WW_Rebinned);		 
   h__MC->Add(TauMTCut_MT2_Higgs_Rebinned);	 
   h__MC->Add(Total200_fromMuTau_MT2_data_Rebinned);

   h__MC->SetLineColor(kWhite);
   h__MC->SetFillColor(kBlack);
   h__MC->SetFillStyle(3004);
   h__MC->Draw("E2 SAME");


   Double_t xAxis6[5] = {40, 50, 70, 90, 120}; 
   
   TH1D *TauMTCut_MT2_data_Rebinned = new TH1D("TauMTCut_MT2_data_Rebinned","",4, xAxis6);
   TauMTCut_MT2_data_Rebinned->SetBinContent(1,11);
   TauMTCut_MT2_data_Rebinned->SetBinContent(2,34);
   TauMTCut_MT2_data_Rebinned->SetBinContent(3,15);
   TauMTCut_MT2_data_Rebinned->SetBinContent(4,3);
   TauMTCut_MT2_data_Rebinned->SetBinContent(5,3);
   TauMTCut_MT2_data_Rebinned->SetBinError(1,3.316625);
   TauMTCut_MT2_data_Rebinned->SetBinError(2,5.830952);
   TauMTCut_MT2_data_Rebinned->SetBinError(3,3.872983);
   TauMTCut_MT2_data_Rebinned->SetBinError(4,2);
   TauMTCut_MT2_data_Rebinned->SetBinError(5,2);
   TauMTCut_MT2_data_Rebinned->SetEntries(68);
   TauMTCut_MT2_data_Rebinned->SetStats(0);
   TauMTCut_MT2_data_Rebinned->SetFillColor(kWhite);
   TauMTCut_MT2_data_Rebinned->SetLineWidth(2);
   TauMTCut_MT2_data_Rebinned->SetMarkerStyle(20);
   TauMTCut_MT2_data_Rebinned->GetXaxis()->SetRange(1,11);
   TauMTCut_MT2_data_Rebinned->GetXaxis()->SetNdivisions(505);
   TauMTCut_MT2_data_Rebinned->GetXaxis()->SetLabelFont(42);
   TauMTCut_MT2_data_Rebinned->GetXaxis()->SetLabelSize(0.07);
   TauMTCut_MT2_data_Rebinned->GetXaxis()->SetTitleSize(0.07);
   TauMTCut_MT2_data_Rebinned->GetXaxis()->SetTitleOffset(1.1);
   TauMTCut_MT2_data_Rebinned->GetXaxis()->SetTitleFont(42);
   TauMTCut_MT2_data_Rebinned->GetYaxis()->SetNdivisions(505);
   TauMTCut_MT2_data_Rebinned->GetYaxis()->SetLabelFont(42);
   TauMTCut_MT2_data_Rebinned->GetYaxis()->SetLabelSize(0.07);
   TauMTCut_MT2_data_Rebinned->GetYaxis()->SetTitleSize(0.07);
   TauMTCut_MT2_data_Rebinned->GetYaxis()->SetTitleOffset(1.3);
   TauMTCut_MT2_data_Rebinned->GetYaxis()->SetTitleFont(42);
   TauMTCut_MT2_data_Rebinned->GetZaxis()->SetLabelFont(42);
   TauMTCut_MT2_data_Rebinned->GetZaxis()->SetLabelSize(0.035);
   TauMTCut_MT2_data_Rebinned->GetZaxis()->SetTitleSize(0.035);
   TauMTCut_MT2_data_Rebinned->GetZaxis()->SetTitleFont(42);
   TauMTCut_MT2_data_Rebinned->Draw("sameE");
   Double_t xAxis7[5] = {40, 50, 70, 90, 120}; 
   
   TH1D *TauMTCut_MT2_SUSY_380_0_Rebinned = new TH1D("TauMTCut_MT2_SUSY_380_0_Rebinned","",4, xAxis7);
   TauMTCut_MT2_SUSY_380_0_Rebinned->SetBinContent(1,0.11693);
   TauMTCut_MT2_SUSY_380_0_Rebinned->SetBinContent(2,0.3424747);
   TauMTCut_MT2_SUSY_380_0_Rebinned->SetBinContent(3,0.3601004);
   TauMTCut_MT2_SUSY_380_0_Rebinned->SetBinContent(4,2.141192);
   TauMTCut_MT2_SUSY_380_0_Rebinned->SetBinContent(5,1.474212);
   TauMTCut_MT2_SUSY_380_0_Rebinned->SetBinError(1,0.02152942);
   TauMTCut_MT2_SUSY_380_0_Rebinned->SetBinError(2,0.04289514);
   TauMTCut_MT2_SUSY_380_0_Rebinned->SetBinError(3,0.03898864);
   TauMTCut_MT2_SUSY_380_0_Rebinned->SetBinError(4,0.1087848);
   TauMTCut_MT2_SUSY_380_0_Rebinned->SetBinError(5,0.09111579);
   TauMTCut_MT2_SUSY_380_0_Rebinned->SetEntries(969);
   TauMTCut_MT2_SUSY_380_0_Rebinned->SetStats(0);
   TauMTCut_MT2_SUSY_380_0_Rebinned->SetLineStyle(3);
   TauMTCut_MT2_SUSY_380_0_Rebinned->SetLineWidth(4);
   TauMTCut_MT2_SUSY_380_0_Rebinned->SetMarkerStyle(20);
   TauMTCut_MT2_SUSY_380_0_Rebinned->GetXaxis()->SetRange(1,11);
   TauMTCut_MT2_SUSY_380_0_Rebinned->GetXaxis()->SetNdivisions(505);
   TauMTCut_MT2_SUSY_380_0_Rebinned->GetXaxis()->SetLabelFont(42);
   TauMTCut_MT2_SUSY_380_0_Rebinned->GetXaxis()->SetLabelSize(0.07);
   TauMTCut_MT2_SUSY_380_0_Rebinned->GetXaxis()->SetTitleSize(0.07);
   TauMTCut_MT2_SUSY_380_0_Rebinned->GetXaxis()->SetTitleOffset(1.1);
   TauMTCut_MT2_SUSY_380_0_Rebinned->GetXaxis()->SetTitleFont(42);
   TauMTCut_MT2_SUSY_380_0_Rebinned->GetYaxis()->SetNdivisions(505);
   TauMTCut_MT2_SUSY_380_0_Rebinned->GetYaxis()->SetLabelFont(42);
   TauMTCut_MT2_SUSY_380_0_Rebinned->GetYaxis()->SetLabelSize(0.07);
   TauMTCut_MT2_SUSY_380_0_Rebinned->GetYaxis()->SetTitleSize(0.07);
   TauMTCut_MT2_SUSY_380_0_Rebinned->GetYaxis()->SetTitleOffset(1.3);
   TauMTCut_MT2_SUSY_380_0_Rebinned->GetYaxis()->SetTitleFont(42);
   TauMTCut_MT2_SUSY_380_0_Rebinned->GetZaxis()->SetLabelFont(42);
   TauMTCut_MT2_SUSY_380_0_Rebinned->GetZaxis()->SetLabelSize(0.035);
   TauMTCut_MT2_SUSY_380_0_Rebinned->GetZaxis()->SetTitleSize(0.035);
   TauMTCut_MT2_SUSY_380_0_Rebinned->GetZaxis()->SetTitleFont(42);
   TauMTCut_MT2_SUSY_380_0_Rebinned->Draw("samehist");

   TLatex *   tex = new TLatex(0.10,0.943,"Preselection, m_{T}^{#tau} > 200 GeV");
   tex->SetNDC();
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
   tex = new TLatex(0.68,0.943,"#sqrt{s} = 8 TeV, L = 19.6 fb^{-1}");
   tex->SetNDC();
   tex->SetTextSize(0.0305);
   tex->SetLineWidth(2);
   tex->Draw();
   tex = new TLatex(0.24,0.85,"CMS Preliminary");
   tex->SetNDC();
   tex->SetLineWidth(2);
   tex->Draw();

   tex = new TLatex(0.26,0.80,"e#tau");
   tex->SetNDC();
   tex->SetLineWidth(2);
   tex->Draw();
   
   TLegend *leg = new TLegend(0.66,0.66,0.91,0.92,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(2);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);

   TLegendEntry *entry;
   entry=leg->AddEntry(TauMTCut_MT2_data_Rebinned,"data","lp");
   entry=leg->AddEntry(Total200_fromMuTau_MT2_data_Rebinned,"W","f");
   entry=leg->AddEntry(TauMTCut_MT2_ZX_Rebinned,"ZX","f");
   entry=leg->AddEntry(TauMTCut_MT2_Top_Rebinned,"Top","f");
   entry=leg->AddEntry(TauMTCut_MT2_WW_Rebinned,"WW","f");
   entry=leg->AddEntry(TauMTCut_MT2_Higgs_Rebinned,"Higgs","f");
   entry=leg->AddEntry(h__MC,"Uncertainties","f");
   entry=leg->AddEntry(TauMTCut_MT2_SUSY_380_0_Rebinned,"SUSY(380,1)","f");
   leg->Draw();
}

// void Plot2(){
  
// // ------------>Primitives in pad: muTau_log_comp_overlay_ratiopad
//    muTau_log_comp_overlay_ratiopad = new TPad("muTau_log_comp_overlay_ratiopad", "Pad containing the ratio",0,0.01863354,0.9967105,0.2189441);
//    muTau_log_comp_overlay_ratiopad->Draw();
//    muTau_log_comp_overlay_ratiopad->cd();
//    muTau_log_comp_overlay_ratiopad->Range(26.48733,-0.8571431,127.5821,2.214286);
//    muTau_log_comp_overlay_ratiopad->SetFillColor(0);
//    muTau_log_comp_overlay_ratiopad->SetBorderMode(0);
//    muTau_log_comp_overlay_ratiopad->SetBorderSize(2);
//    muTau_log_comp_overlay_ratiopad->SetLeftMargin(0.1336634);
//    muTau_log_comp_overlay_ratiopad->SetRightMargin(0.075);
//    muTau_log_comp_overlay_ratiopad->SetTopMargin(0.06976745);
//    muTau_log_comp_overlay_ratiopad->SetBottomMargin(0.2790698);
//    muTau_log_comp_overlay_ratiopad->SetFrameLineWidth(3);
//    muTau_log_comp_overlay_ratiopad->SetFrameBorderMode(0);
//    muTau_log_comp_overlay_ratiopad->SetFrameBorderSize(0);
//    muTau_log_comp_overlay_ratiopad->SetFrameLineWidth(3);
//    muTau_log_comp_overlay_ratiopad->SetFrameBorderMode(0);
//    muTau_log_comp_overlay_ratiopad->SetFrameBorderSize(0);
//    Double_t xAxis8[5] = {40, 50, 70, 90, 120}; 
   
//    TH1D *h__MC = new TH1D("h__MC","",4, xAxis8);
//    h__MC->SetBinContent(0,1);
//    h__MC->SetBinContent(1,1);
//    h__MC->SetBinContent(2,1);
//    h__MC->SetBinContent(3,1);
//    h__MC->SetBinContent(4,1);
//    h__MC->SetBinContent(5,1);
//    h__MC->SetBinError(0,0.460838);
//    h__MC->SetBinError(1,1.440343);
//    h__MC->SetBinError(2,0.3969686);
//    h__MC->SetBinError(3,0.7437075);
//    h__MC->SetBinError(4,1.327108);
//    h__MC->SetBinError(5,1.429058);
//    h__MC->SetMinimum(0);
//    h__MC->SetMaximum(2);
//    h__MC->SetEntries(3.519199);
//    h__MC->SetStats(0);
//    h__MC->SetFillColor(1);
//    h__MC->SetFillStyle(3004);

//    ci = TColor::GetColor("#000099");
//    h__MC->SetLineColor(ci);
//    h__MC->SetLineWidth(2);
//    h__MC->GetXaxis()->SetTitle("M_{T2}");
//    h__MC->GetXaxis()->SetRange(1,4);
//    h__MC->GetXaxis()->SetNdivisions(505);
//    h__MC->GetXaxis()->SetLabelFont(42);
//    h__MC->GetXaxis()->SetLabelSize(0);
//    h__MC->GetXaxis()->SetTitleSize(0.2);
//    h__MC->GetXaxis()->SetTickLength(0.09);
//    h__MC->GetXaxis()->SetTitleOffset(0.5);
//    h__MC->GetXaxis()->SetTitleFont(42);
//    h__MC->GetYaxis()->SetTitle("Data / MC");
//    h__MC->GetYaxis()->SetNdivisions(509);
//    h__MC->GetYaxis()->SetLabelFont(42);
//    h__MC->GetYaxis()->SetLabelSize(0.19);
//    h__MC->GetYaxis()->SetTitleSize(0.18);
//    h__MC->GetYaxis()->SetTitleOffset(0.36);
//    h__MC->GetYaxis()->SetTitleFont(42);
//    h__MC->GetZaxis()->SetLabelFont(42);
//    h__MC->GetZaxis()->SetLabelSize(0.035);
//    h__MC->GetZaxis()->SetTitleSize(0.035);
//    h__MC->GetZaxis()->SetTitleFont(42);
//    h__MC->Draw("E2");
//    Double_t xAxis9[5] = {40, 50, 70, 90, 120}; 
   
//    TH1D *TauMTCut_MT2_data_Rebinned__1 = new TH1D("TauMTCut_MT2_data_Rebinned__1","",4, xAxis9);
//    TauMTCut_MT2_data_Rebinned__1->SetBinContent(1,2.931791);
//    TauMTCut_MT2_data_Rebinned__1->SetBinContent(2,1.07983);
//    TauMTCut_MT2_data_Rebinned__1->SetBinContent(3,1.511532);
//    TauMTCut_MT2_data_Rebinned__1->SetBinContent(4,1.013628);
//    TauMTCut_MT2_data_Rebinned__1->SetBinContent(5,1.09187);
//    TauMTCut_MT2_data_Rebinned__1->SetBinError(1,3.114058);
//    TauMTCut_MT2_data_Rebinned__1->SetBinError(2,0.355203);
//    TauMTCut_MT2_data_Rebinned__1->SetBinError(3,0.8855267);
//    TauMTCut_MT2_data_Rebinned__1->SetBinError(4,1.166797);
//    TauMTCut_MT2_data_Rebinned__1->SetBinError(5,1.321816);
//    TauMTCut_MT2_data_Rebinned__1->SetMinimum(0.4);
//    TauMTCut_MT2_data_Rebinned__1->SetMaximum(3);
//    TauMTCut_MT2_data_Rebinned__1->SetEntries(2.397098);
//    TauMTCut_MT2_data_Rebinned__1->SetDirectory(0);
//    TauMTCut_MT2_data_Rebinned__1->SetStats(0);

//    ci = TColor::GetColor("#ff0000");
//    TauMTCut_MT2_data_Rebinned__1->SetFillColor(ci);
//    TauMTCut_MT2_data_Rebinned__1->SetLineWidth(2);
//    TauMTCut_MT2_data_Rebinned__1->SetMarkerStyle(20);
//    TauMTCut_MT2_data_Rebinned__1->GetXaxis()->SetRange(1,11);
//    TauMTCut_MT2_data_Rebinned__1->GetXaxis()->SetNdivisions(505);
//    TauMTCut_MT2_data_Rebinned__1->GetXaxis()->SetLabelFont(42);
//    TauMTCut_MT2_data_Rebinned__1->GetXaxis()->SetLabelSize(0.07);
//    TauMTCut_MT2_data_Rebinned__1->GetXaxis()->SetTitleSize(0.07);
//    TauMTCut_MT2_data_Rebinned__1->GetXaxis()->SetTitleOffset(1.1);
//    TauMTCut_MT2_data_Rebinned__1->GetXaxis()->SetTitleFont(42);
//    TauMTCut_MT2_data_Rebinned__1->GetYaxis()->SetNdivisions(505);
//    TauMTCut_MT2_data_Rebinned__1->GetYaxis()->SetLabelFont(42);
//    TauMTCut_MT2_data_Rebinned__1->GetYaxis()->SetLabelSize(0.07);
//    TauMTCut_MT2_data_Rebinned__1->GetYaxis()->SetTitleSize(0.07);
//    TauMTCut_MT2_data_Rebinned__1->GetYaxis()->SetTitleOffset(1.3);
//    TauMTCut_MT2_data_Rebinned__1->GetYaxis()->SetTitleFont(42);
//    TauMTCut_MT2_data_Rebinned__1->GetZaxis()->SetLabelFont(42);
//    TauMTCut_MT2_data_Rebinned__1->GetZaxis()->SetLabelSize(0.035);
//    TauMTCut_MT2_data_Rebinned__1->GetZaxis()->SetTitleSize(0.035);
//    TauMTCut_MT2_data_Rebinned__1->GetZaxis()->SetTitleFont(42);
//    TauMTCut_MT2_data_Rebinned__1->Draw("Esame");
//    TLine *line = new TLine(40,1,120,1);
//    line->SetLineStyle(7);
//    line->SetLineWidth(2);
//    line->Draw();
//    muTau_log_comp_overlay_ratiopad->Modified();
//    muTau_log_comp_overlayc_ratio->cd();
//    muTau_log_comp_overlayc_ratio->Modified();
//    muTau_log_comp_overlayc_ratio->cd();
//    muTau_log_comp_overlayc_ratio->SetSelected(muTau_log_comp_overlayc_ratio);
//    muTau_log_comp_overlayc_ratio->ToggleToolBar();
// }
