{
//=========Macro generated from canvas: MT2_ratioc_ratio/
//=========  (Sat Dec  5 16:38:20 2015) by ROOT version5.34/03
   TCanvas *MT2_ratioc_ratio = new TCanvas("MT2_ratioc_ratio", "",66,52,600,630);
   gStyle->SetOptFit(1);
   MT2_ratioc_ratio->Range(0,0,1,1);
   MT2_ratioc_ratio->SetFillColor(0);
   MT2_ratioc_ratio->SetBorderMode(0);
   MT2_ratioc_ratio->SetBorderSize(2);
   MT2_ratioc_ratio->SetLeftMargin(0.18);
   MT2_ratioc_ratio->SetRightMargin(0.08);
   MT2_ratioc_ratio->SetTopMargin(0.07);
   MT2_ratioc_ratio->SetBottomMargin(0.17);
   MT2_ratioc_ratio->SetFrameBorderMode(0);
   MT2_ratioc_ratio->SetFrameBorderSize(0);
  
// ------------>Primitives in pad: MT2_ratio_plotpad
   TPad *MT2_ratio_plotpad = new TPad("MT2_ratio_plotpad", "Pad containing the overlay plot",0,0.211838,1,1);
   MT2_ratio_plotpad->Draw();
   MT2_ratio_plotpad->cd();
   MT2_ratio_plotpad->Range(66.62215,-2.606783,320.2937,3.16839);
   MT2_ratio_plotpad->SetFillColor(0);
   MT2_ratio_plotpad->SetFillStyle(4000);
   MT2_ratio_plotpad->SetBorderMode(0);
   MT2_ratio_plotpad->SetBorderSize(2);
   MT2_ratio_plotpad->SetLogy();
   MT2_ratio_plotpad->SetLeftMargin(0.131579);
   MT2_ratio_plotpad->SetRightMargin(0.08);
   MT2_ratio_plotpad->SetTopMargin(0.06895515);
   MT2_ratio_plotpad->SetBottomMargin(0.07206074);
   MT2_ratio_plotpad->SetFrameLineWidth(3);
   MT2_ratio_plotpad->SetFrameBorderMode(0);
   MT2_ratio_plotpad->SetFrameBorderSize(0);
   MT2_ratio_plotpad->SetFrameLineWidth(3);
   MT2_ratio_plotpad->SetFrameBorderMode(0);
   MT2_ratio_plotpad->SetFrameBorderSize(0);
   
   THStack *summt = new THStack();
   summt->SetName("summt");
   summt->SetTitle("");
   summt->SetMinimum(0.02);
   summt->SetMaximum(320);
   
   TH1F *summt_stack_1 = new TH1F("summt_stack_1","",4,100,300);
   summt_stack_1->SetMinimum(0.006447329);
   summt_stack_1->SetMaximum(589.0637);
   summt_stack_1->SetDirectory(0);
   summt_stack_1->SetStats(0);
   summt_stack_1->SetLineWidth(2);
   summt_stack_1->GetXaxis()->SetTitle("#Sigma m_{T}^{#tau_{i}}");
   summt_stack_1->GetXaxis()->SetNdivisions(505);
   summt_stack_1->GetXaxis()->SetLabelFont(42);
   summt_stack_1->GetXaxis()->SetLabelSize(0.05);
   summt_stack_1->GetXaxis()->SetTitleSize(0.05);
   summt_stack_1->GetXaxis()->SetTitleOffset(1.1);
   summt_stack_1->GetXaxis()->SetTitleFont(42);
   summt_stack_1->GetYaxis()->SetTitle("Events");
   summt_stack_1->GetYaxis()->SetNdivisions(505);
   summt_stack_1->GetYaxis()->SetLabelFont(42);
   summt_stack_1->GetYaxis()->SetLabelSize(0.05);
   summt_stack_1->GetYaxis()->SetTitleSize(0.05);
   summt_stack_1->GetYaxis()->SetTitleOffset(1.3);
   summt_stack_1->GetYaxis()->SetTitleFont(42);
   summt_stack_1->GetZaxis()->SetLabelFont(42);
   summt_stack_1->GetZaxis()->SetLabelSize(0.035);
   summt_stack_1->GetZaxis()->SetTitleSize(0.035);
   summt_stack_1->GetZaxis()->SetTitleFont(42);
   summt->SetHistogram(summt_stack_1);
   
   Double_t xAxis1[5] = {100, 150, 200, 250, 300}; 
   
   TH1D *summt_Higgs = new TH1D("summt_Higgs","",4, xAxis1);
   summt_Higgs->SetBinContent(1,0.07092376);
   summt_Higgs->SetBinContent(2,0.318799);
   summt_Higgs->SetBinContent(3,0.07742545);
   summt_Higgs->SetBinContent(4,0.07488839);
   summt_Higgs->SetBinError(1,0.04990565);
   summt_Higgs->SetBinError(2,0.1784332);
   summt_Higgs->SetBinError(3,0.05062611);
   summt_Higgs->SetBinError(4,0.04417018);
   summt_Higgs->SetEntries(64);
   summt_Higgs->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff0000");
   summt_Higgs->SetFillColor(ci);

   ci = TColor::GetColor("#ff0000");
   summt_Higgs->SetLineColor(ci);
   summt_Higgs->SetLineWidth(2);

   ci = TColor::GetColor("#ff0000");
   summt_Higgs->SetMarkerColor(ci);
   summt_Higgs->GetXaxis()->SetNdivisions(505);
   summt_Higgs->GetXaxis()->SetLabelFont(42);
   summt_Higgs->GetXaxis()->SetLabelSize(0.07);
   summt_Higgs->GetXaxis()->SetTitleSize(0.07);
   summt_Higgs->GetXaxis()->SetTitleOffset(1.1);
   summt_Higgs->GetXaxis()->SetTitleFont(42);
   summt_Higgs->GetYaxis()->SetNdivisions(505);
   summt_Higgs->GetYaxis()->SetLabelFont(42);
   summt_Higgs->GetYaxis()->SetLabelSize(0.07);
   summt_Higgs->GetYaxis()->SetTitleSize(0.07);
   summt_Higgs->GetYaxis()->SetTitleOffset(1.3);
   summt_Higgs->GetYaxis()->SetTitleFont(42);
   summt_Higgs->GetZaxis()->SetLabelFont(42);
   summt_Higgs->GetZaxis()->SetLabelSize(0.035);
   summt_Higgs->GetZaxis()->SetTitleSize(0.035);
   summt_Higgs->GetZaxis()->SetTitleFont(42);
   summt->Add(summt_Higgs,"");
   Double_t xAxis2[5] = {100, 150, 200, 250, 300}; 
   
   TH1D *summt_WW = new TH1D("summt_WW","",4, xAxis2);
   summt_WW->SetBinContent(2,0.270886);
   summt_WW->SetBinContent(3,0.4698851);
   summt_WW->SetBinContent(4,0.1483787);
   summt_WW->SetBinError(2,0.170654);
   summt_WW->SetBinError(3,0.270473);
   summt_WW->SetBinError(4,0.102007);
   summt_WW->SetEntries(19);
   summt_WW->SetStats(0);

   ci = TColor::GetColor("#000066");
   summt_WW->SetFillColor(ci);

   ci = TColor::GetColor("#000066");
   summt_WW->SetLineColor(ci);
   summt_WW->SetLineWidth(2);

   ci = TColor::GetColor("#000066");
   summt_WW->SetMarkerColor(ci);
   summt_WW->GetXaxis()->SetNdivisions(505);
   summt_WW->GetXaxis()->SetLabelFont(42);
   summt_WW->GetXaxis()->SetLabelSize(0.07);
   summt_WW->GetXaxis()->SetTitleSize(0.07);
   summt_WW->GetXaxis()->SetTitleOffset(1.1);
   summt_WW->GetXaxis()->SetTitleFont(42);
   summt_WW->GetYaxis()->SetNdivisions(505);
   summt_WW->GetYaxis()->SetLabelFont(42);
   summt_WW->GetYaxis()->SetLabelSize(0.07);
   summt_WW->GetYaxis()->SetTitleSize(0.07);
   summt_WW->GetYaxis()->SetTitleOffset(1.3);
   summt_WW->GetYaxis()->SetTitleFont(42);
   summt_WW->GetZaxis()->SetLabelFont(42);
   summt_WW->GetZaxis()->SetLabelSize(0.035);
   summt_WW->GetZaxis()->SetTitleSize(0.035);
   summt_WW->GetZaxis()->SetTitleFont(42);
   summt->Add(summt_WW,"");
   Double_t xAxis3[5] = {100, 150, 200, 250, 300}; 
   
   TH1D *summt_Top = new TH1D("summt_Top","",4, xAxis3);
   summt_Top->SetBinContent(2,0.2561433);
   summt_Top->SetBinContent(3,0.001803654);
   summt_Top->SetBinContent(4,0.5268298);
   summt_Top->SetBinError(2,0.2863769);
   summt_Top->SetBinError(3,0.002016546);
   summt_Top->SetBinError(4,0.5890136);
   summt_Top->SetEntries(184);
   summt_Top->SetStats(0);

   ci = TColor::GetColor("#3366cc");
   summt_Top->SetFillColor(ci);

   ci = TColor::GetColor("#3366cc");
   summt_Top->SetLineColor(ci);
   summt_Top->SetLineWidth(2);

   ci = TColor::GetColor("#3366cc");
   summt_Top->SetMarkerColor(ci);
   summt_Top->GetXaxis()->SetNdivisions(505);
   summt_Top->GetXaxis()->SetLabelFont(42);
   summt_Top->GetXaxis()->SetLabelSize(0.07);
   summt_Top->GetXaxis()->SetTitleSize(0.07);
   summt_Top->GetXaxis()->SetTitleOffset(1.1);
   summt_Top->GetXaxis()->SetTitleFont(42);
   summt_Top->GetYaxis()->SetNdivisions(505);
   summt_Top->GetYaxis()->SetLabelFont(42);
   summt_Top->GetYaxis()->SetLabelSize(0.07);
   summt_Top->GetYaxis()->SetTitleSize(0.07);
   summt_Top->GetYaxis()->SetTitleOffset(1.3);
   summt_Top->GetYaxis()->SetTitleFont(42);
   summt_Top->GetZaxis()->SetLabelFont(42);
   summt_Top->GetZaxis()->SetLabelSize(0.035);
   summt_Top->GetZaxis()->SetTitleSize(0.035);
   summt_Top->GetZaxis()->SetTitleFont(42);
   summt->Add(summt_Top,"");
   Double_t xAxis4[5] = {100, 150, 200, 250, 300}; 
   
   TH1D *summt_ZX = new TH1D("summt_ZX","",4, xAxis4);
   summt_ZX->SetBinContent(1,1.158208);
   summt_ZX->SetBinContent(2,4.615497);
   summt_ZX->SetBinContent(3,1.13796);
   summt_ZX->SetBinContent(4,0.8086002);
   summt_ZX->SetBinError(1,0.7376637);
   summt_ZX->SetBinError(2,1.813091);
   summt_ZX->SetBinError(3,0.4799247);
   summt_ZX->SetBinError(4,0.5990081);
   summt_ZX->SetBinError(5,0.01049275);
   summt_ZX->SetEntries(224);
   summt_ZX->SetStats(0);

   ci = TColor::GetColor("#006600");
   summt_ZX->SetFillColor(ci);

   ci = TColor::GetColor("#006600");
   summt_ZX->SetLineColor(ci);
   summt_ZX->SetLineWidth(2);

   ci = TColor::GetColor("#006600");
   summt_ZX->SetMarkerColor(ci);
   summt_ZX->GetXaxis()->SetNdivisions(505);
   summt_ZX->GetXaxis()->SetLabelFont(42);
   summt_ZX->GetXaxis()->SetLabelSize(0.07);
   summt_ZX->GetXaxis()->SetTitleSize(0.07);
   summt_ZX->GetXaxis()->SetTitleOffset(1.1);
   summt_ZX->GetXaxis()->SetTitleFont(42);
   summt_ZX->GetYaxis()->SetNdivisions(505);
   summt_ZX->GetYaxis()->SetLabelFont(42);
   summt_ZX->GetYaxis()->SetLabelSize(0.07);
   summt_ZX->GetYaxis()->SetTitleSize(0.07);
   summt_ZX->GetYaxis()->SetTitleOffset(1.3);
   summt_ZX->GetYaxis()->SetTitleFont(42);
   summt_ZX->GetZaxis()->SetLabelFont(42);
   summt_ZX->GetZaxis()->SetLabelSize(0.035);
   summt_ZX->GetZaxis()->SetTitleSize(0.035);
   summt_ZX->GetZaxis()->SetTitleFont(42);
   summt->Add(summt_ZX,"");
   Double_t xAxis5[5] = {100, 150, 200, 250, 300}; 
   
   TH1D *summt_W = new TH1D("summt_W","",4, xAxis5);
   summt_W->SetBinContent(2,15.56548);
   summt_W->SetBinContent(3,13.13984);
   summt_W->SetBinContent(4,2.7);
   summt_W->SetBinError(2,5.872039);
   summt_W->SetBinError(3,5.474625);
   summt_W->SetBinError(4,1.0071);
   summt_W->SetEntries(79);
   summt_W->SetStats(0);

   ci = TColor::GetColor("#00cc00");
   summt_W->SetFillColor(ci);

   ci = TColor::GetColor("#00cc00");
   summt_W->SetLineColor(ci);
   summt_W->SetLineWidth(2);

   ci = TColor::GetColor("#00cc00");
   summt_W->SetMarkerColor(ci);
   summt_W->GetXaxis()->SetNdivisions(505);
   summt_W->GetXaxis()->SetLabelFont(42);
   summt_W->GetXaxis()->SetLabelSize(0.07);
   summt_W->GetXaxis()->SetTitleSize(0.07);
   summt_W->GetXaxis()->SetTitleOffset(1.1);
   summt_W->GetXaxis()->SetTitleFont(42);
   summt_W->GetYaxis()->SetNdivisions(505);
   summt_W->GetYaxis()->SetLabelFont(42);
   summt_W->GetYaxis()->SetLabelSize(0.07);
   summt_W->GetYaxis()->SetTitleSize(0.07);
   summt_W->GetYaxis()->SetTitleOffset(1.3);
   summt_W->GetYaxis()->SetTitleFont(42);
   summt_W->GetZaxis()->SetLabelFont(42);
   summt_W->GetZaxis()->SetLabelSize(0.035);
   summt_W->GetZaxis()->SetTitleSize(0.035);
   summt_W->GetZaxis()->SetTitleFont(42);
   summt->Add(summt_W,"");
   Double_t xAxis6[5] = {100, 150, 200, 250, 300}; 
   
   TH1D *summt_QCD = new TH1D("summt_QCD","",4, xAxis6);
   summt_QCD->SetBinContent(1,11.748);
   summt_QCD->SetBinContent(2,42.68843);
   summt_QCD->SetBinContent(3,6.396727);
   summt_QCD->SetBinContent(4,1.15);
   summt_QCD->SetBinError(1,4.123398);
   summt_QCD->SetBinError(2,9.416249);
   summt_QCD->SetBinError(3,3.805273);
   summt_QCD->SetBinError(4,0.85);
   summt_QCD->SetEntries(84);
   summt_QCD->SetStats(0);

   ci = TColor::GetColor("#cccc00");
   summt_QCD->SetFillColor(ci);

   ci = TColor::GetColor("#cccc00");
   summt_QCD->SetLineColor(ci);
   summt_QCD->SetLineWidth(2);

   ci = TColor::GetColor("#cccc00");
   summt_QCD->SetMarkerColor(ci);
   summt_QCD->GetXaxis()->SetNdivisions(505);
   summt_QCD->GetXaxis()->SetLabelFont(42);
   summt_QCD->GetXaxis()->SetLabelSize(0.07);
   summt_QCD->GetXaxis()->SetTitleSize(0.07);
   summt_QCD->GetXaxis()->SetTitleOffset(1.1);
   summt_QCD->GetXaxis()->SetTitleFont(42);
   summt_QCD->GetYaxis()->SetNdivisions(505);
   summt_QCD->GetYaxis()->SetLabelFont(42);
   summt_QCD->GetYaxis()->SetLabelSize(0.07);
   summt_QCD->GetYaxis()->SetTitleSize(0.07);
   summt_QCD->GetYaxis()->SetTitleOffset(1.3);
   summt_QCD->GetYaxis()->SetTitleFont(42);
   summt_QCD->GetZaxis()->SetLabelFont(42);
   summt_QCD->GetZaxis()->SetLabelSize(0.035);
   summt_QCD->GetZaxis()->SetTitleSize(0.035);
   summt_QCD->GetZaxis()->SetTitleFont(42);
   summt->Add(summt_QCD,"");
   summt->Draw("hist");
   Double_t xAxis7[5] = {100, 150, 200, 250, 300}; 
   
   TH1D *h2_copy = new TH1D("h2_copy","",4, xAxis7);
   h2_copy->SetBinContent(1,15);
   h2_copy->SetBinContent(2,64);
   h2_copy->SetBinContent(3,13);
   h2_copy->SetBinContent(4,2);
   h2_copy->SetBinError(1,3.872983);
   h2_copy->SetBinError(2,8);
   h2_copy->SetBinError(3,3.605551);
   h2_copy->SetBinError(4,1.414214);
   h2_copy->SetMinimum(0.05);
   h2_copy->SetMaximum(320);
   h2_copy->SetEntries(114);
   h2_copy->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   h2_copy->SetFillColor(ci);
   h2_copy->SetLineWidth(2);
   h2_copy->SetMarkerStyle(20);
   h2_copy->GetXaxis()->SetNdivisions(505);
   h2_copy->GetXaxis()->SetLabelFont(42);
   h2_copy->GetXaxis()->SetLabelSize(0.07);
   h2_copy->GetXaxis()->SetTitleSize(0.07);
   h2_copy->GetXaxis()->SetTitleOffset(1.1);
   h2_copy->GetXaxis()->SetTitleFont(42);
   h2_copy->GetYaxis()->SetNdivisions(505);
   h2_copy->GetYaxis()->SetLabelFont(42);
   h2_copy->GetYaxis()->SetLabelSize(0.07);
   h2_copy->GetYaxis()->SetTitleSize(0.07);
   h2_copy->GetYaxis()->SetTitleOffset(1.3);
   h2_copy->GetYaxis()->SetTitleFont(42);
   h2_copy->GetZaxis()->SetLabelFont(42);
   h2_copy->GetZaxis()->SetLabelSize(0.035);
   h2_copy->GetZaxis()->SetTitleSize(0.035);
   h2_copy->GetZaxis()->SetTitleFont(42);
   h2_copy->Draw("sameE");
   Double_t xAxis8[5] = {100, 150, 200, 250, 300}; 
   
   TH1D *summt_susy = new TH1D("summt_susy","",4, xAxis8);
   summt_susy->SetBinContent(2,0.6868009);
   summt_susy->SetBinContent(3,2.489492);
   summt_susy->SetBinContent(4,3.597845);
   summt_susy->SetBinError(2,0.1304177);
   summt_susy->SetBinError(3,0.2751065);
   summt_susy->SetBinError(4,0.358849);
   summt_susy->SetBinError(5,0.1757565);
   summt_susy->SetEntries(419);
   summt_susy->SetStats(0);
   summt_susy->SetLineStyle(3);
   summt_susy->SetLineWidth(3);
   summt_susy->GetXaxis()->SetNdivisions(505);
   summt_susy->GetXaxis()->SetLabelFont(42);
   summt_susy->GetXaxis()->SetLabelSize(0.07);
   summt_susy->GetXaxis()->SetTitleSize(0.07);
   summt_susy->GetXaxis()->SetTitleOffset(1.1);
   summt_susy->GetXaxis()->SetTitleFont(42);
   summt_susy->GetYaxis()->SetNdivisions(505);
   summt_susy->GetYaxis()->SetLabelFont(42);
   summt_susy->GetYaxis()->SetLabelSize(0.07);
   summt_susy->GetYaxis()->SetTitleSize(0.07);
   summt_susy->GetYaxis()->SetTitleOffset(1.3);
   summt_susy->GetYaxis()->SetTitleFont(42);
   summt_susy->GetZaxis()->SetLabelFont(42);
   summt_susy->GetZaxis()->SetLabelSize(0.035);
   summt_susy->GetZaxis()->SetTitleSize(0.035);
   summt_susy->GetZaxis()->SetTitleFont(42);
   summt_susy->Draw("samehist");
   TLatex *   tex = new TLatex(0.795302,0.6384436,"0 jets");
tex->SetNDC();
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.68,0.943,"#sqrt{s} = 8 TeV, L = 18.10 fb^{-1}");
tex->SetNDC();
   tex->SetTextSize(0.0305);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *summt__1 = new TH1F("summt__1","",4,100,300);
   summt__1->SetMinimum(0.006447329);
   summt__1->SetMaximum(589.0637);
   summt__1->SetDirectory(0);
   summt__1->SetStats(0);
   summt__1->SetLineWidth(2);
   summt__1->GetXaxis()->SetTitle("#Sigma m_{T}^{#tau_{i}}");
   summt__1->GetXaxis()->SetNdivisions(505);
   summt__1->GetXaxis()->SetLabelFont(42);
   summt__1->GetXaxis()->SetLabelSize(0.05);
   summt__1->GetXaxis()->SetTitleSize(0.05);
   summt__1->GetXaxis()->SetTitleOffset(1.1);
   summt__1->GetXaxis()->SetTitleFont(42);
   summt__1->GetYaxis()->SetTitle("Events");
   summt__1->GetYaxis()->SetNdivisions(505);
   summt__1->GetYaxis()->SetLabelFont(42);
   summt__1->GetYaxis()->SetLabelSize(0.05);
   summt__1->GetYaxis()->SetTitleSize(0.05);
   summt__1->GetYaxis()->SetTitleOffset(1.3);
   summt__1->GetYaxis()->SetTitleFont(42);
   summt__1->GetZaxis()->SetLabelFont(42);
   summt__1->GetZaxis()->SetLabelSize(0.035);
   summt__1->GetZaxis()->SetTitleSize(0.035);
   summt__1->GetZaxis()->SetTitleFont(42);
   summt__1->Draw("sameaxis");
   
   TLegend *leg = new TLegend(0.7097315,0.7182965,0.909396,0.920147,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(2);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("summt_Higgs","Higgs","f");

   ci = TColor::GetColor("#ff0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("summt_WW","WW","f");

   ci = TColor::GetColor("#000066");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000066");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("summt_Top","Top","f");

   ci = TColor::GetColor("#3366cc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#3366cc");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("summt_ZX","ZX","f");

   ci = TColor::GetColor("#006600");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#006600");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("summt_W","W","f");

   ci = TColor::GetColor("#00cc00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00cc00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("summt_QCD","QCD","f");

   ci = TColor::GetColor("#cccc00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#cccc00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("summt_susy","SMS","l");
   entry->SetLineColor(1);
   entry->SetLineStyle(3);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("summt_data","data","l");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
  
// ------------>Primitives in pad: MT2_ratio_plotpad_1
   MT2_ratio_plotpad_1 = new TPad("MT2_ratio_plotpad_1", "newpad",0.7869128,0.6155556,0.885906,0.6844444);
   MT2_ratio_plotpad_1->Draw();
   MT2_ratio_plotpad_1->cd();
   MT2_ratio_plotpad_1->Range(0,0,1,1);
   MT2_ratio_plotpad_1->SetFillColor(0);
   MT2_ratio_plotpad_1->SetBorderMode(0);
   MT2_ratio_plotpad_1->SetBorderSize(2);
   MT2_ratio_plotpad_1->SetLeftMargin(0.18);
   MT2_ratio_plotpad_1->SetRightMargin(0.08);
   MT2_ratio_plotpad_1->SetTopMargin(0.07);
   MT2_ratio_plotpad_1->SetBottomMargin(0.17);
   MT2_ratio_plotpad_1->SetFrameLineWidth(3);
   MT2_ratio_plotpad_1->SetFrameBorderMode(0);
   MT2_ratio_plotpad_1->SetFrameBorderSize(0);
   MT2_ratio_plotpad_1->Modified();
   MT2_ratio_plotpad->cd();
      tex = new TLatex(125.7838,171.1003,"CMS Preliminary");
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(211.7597,176.2223,"#tau#tau");
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(100.2464,747.7514,"Preselection, MT2<90, bjet veto");
   tex->SetTextSize(0.03992648);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(269.6445,66.57736,"SS");
   tex->SetTextSize(0.03105393);
   tex->SetLineWidth(2);
   tex->Draw();
   MT2_ratio_plotpad->Modified();
   MT2_ratioc_ratio->cd();
  
// ------------>Primitives in pad: MT2_ratio_ratiopad
   MT2_ratio_ratiopad = new TPad("MT2_ratio_ratiopad", "Pad containing the ratio",0,0.01863354,0.9967105,0.2189441);
   MT2_ratio_ratiopad->Draw();
   MT2_ratio_ratiopad->cd();
   MT2_ratio_ratiopad->Range(66.21832,-0.8571431,318.9553,2.214286);
   MT2_ratio_ratiopad->SetFillColor(0);
   MT2_ratio_ratiopad->SetBorderMode(0);
   MT2_ratio_ratiopad->SetBorderSize(2);
   MT2_ratio_ratiopad->SetLeftMargin(0.1336634);
   MT2_ratio_ratiopad->SetRightMargin(0.075);
   MT2_ratio_ratiopad->SetTopMargin(0.06976745);
   MT2_ratio_ratiopad->SetBottomMargin(0.2790698);
   MT2_ratio_ratiopad->SetFrameLineWidth(3);
   MT2_ratio_ratiopad->SetFrameBorderMode(0);
   MT2_ratio_ratiopad->SetFrameBorderSize(0);
   MT2_ratio_ratiopad->SetFrameLineWidth(3);
   MT2_ratio_ratiopad->SetFrameBorderMode(0);
   MT2_ratio_ratiopad->SetFrameBorderSize(0);
   Double_t xAxis9[5] = {100, 150, 200, 250, 300}; 
   
   TH1D *h1_copy = new TH1D("h1_copy","",4, xAxis9);
   h1_copy->SetBinContent(1,1);
   h1_copy->SetBinContent(2,1);
   h1_copy->SetBinContent(3,1);
   h1_copy->SetBinContent(4,1);
   h1_copy->SetBinError(1,0.4565234);
   h1_copy->SetBinError(2,0.2497174);
   h1_copy->SetBinError(3,0.4457885);
   h1_copy->SetBinError(4,0.409671);
   h1_copy->SetMinimum(0);
   h1_copy->SetMaximum(2);
   h1_copy->SetEntries(25.10473);
   h1_copy->SetStats(0);
   h1_copy->SetFillColor(1);
   h1_copy->SetFillStyle(3001);
   h1_copy->SetLineColor(ci);
   h1_copy->SetLineWidth(2);
   h1_copy->SetMarkerColor(ci);
   h1_copy->GetXaxis()->SetTitle("#Sigma m_{T}^{#tau_{i}}");
   h1_copy->GetXaxis()->SetNdivisions(505);
   h1_copy->GetXaxis()->SetLabelFont(42);
   h1_copy->GetXaxis()->SetLabelSize(0);
   h1_copy->GetXaxis()->SetTitleSize(0.2);
   h1_copy->GetXaxis()->SetTickLength(0.09);
   h1_copy->GetXaxis()->SetTitleOffset(0.5);
   h1_copy->GetXaxis()->SetTitleFont(42);
   h1_copy->GetYaxis()->SetTitle("Data / MC");
   h1_copy->GetYaxis()->SetNdivisions(509);
   h1_copy->GetYaxis()->SetLabelFont(42);
   h1_copy->GetYaxis()->SetLabelSize(0.19);
   h1_copy->GetYaxis()->SetTitleSize(0.18);
   h1_copy->GetYaxis()->SetTitleOffset(0.36);
   h1_copy->GetYaxis()->SetTitleFont(42);
   h1_copy->GetZaxis()->SetLabelFont(42);
   h1_copy->GetZaxis()->SetLabelSize(0.035);
   h1_copy->GetZaxis()->SetTitleSize(0.035);
   h1_copy->GetZaxis()->SetTitleFont(42);
   h1_copy->Draw("E2");
   Double_t xAxis10[5] = {100, 150, 200, 250, 300}; 
   
   TH1D *h2_copy__2 = new TH1D("h2_copy__2","",4, xAxis10);
   h2_copy__2->SetBinContent(1,1.155879);
   h2_copy__2->SetBinContent(2,1.004469);
   h2_copy__2->SetBinContent(3,0.6125245);
   h2_copy__2->SetBinContent(4,0.3697748);
   h2_copy__2->SetBinError(1,0.4778041);
   h2_copy__2->SetBinError(2,0.2173102);
   h2_copy__2->SetBinError(3,0.2571777);
   h2_copy__2->SetBinError(4,0.282561);
   h2_copy__2->SetMinimum(0.4);
   h2_copy__2->SetMaximum(3);
   h2_copy__2->SetEntries(23.43108);
   h2_copy__2->SetDirectory(0);
   h2_copy__2->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   h2_copy__2->SetFillColor(ci);
   h2_copy__2->SetLineWidth(2);
   h2_copy__2->SetMarkerStyle(20);
   h2_copy__2->GetXaxis()->SetNdivisions(505);
   h2_copy__2->GetXaxis()->SetLabelFont(42);
   h2_copy__2->GetXaxis()->SetLabelSize(0.07);
   h2_copy__2->GetXaxis()->SetTitleSize(0.07);
   h2_copy__2->GetXaxis()->SetTitleOffset(1.1);
   h2_copy__2->GetXaxis()->SetTitleFont(42);
   h2_copy__2->GetYaxis()->SetNdivisions(505);
   h2_copy__2->GetYaxis()->SetLabelFont(42);
   h2_copy__2->GetYaxis()->SetLabelSize(0.07);
   h2_copy__2->GetYaxis()->SetTitleSize(0.07);
   h2_copy__2->GetYaxis()->SetTitleOffset(1.3);
   h2_copy__2->GetYaxis()->SetTitleFont(42);
   h2_copy__2->GetZaxis()->SetLabelFont(42);
   h2_copy__2->GetZaxis()->SetLabelSize(0.035);
   h2_copy__2->GetZaxis()->SetTitleSize(0.035);
   h2_copy__2->GetZaxis()->SetTitleFont(42);
   h2_copy__2->Draw("Esame");
   TLine *line = new TLine(100,1,300,1);
   line->SetLineStyle(7);
   line->SetLineWidth(2);
   line->Draw();
   Double_t xAxis11[5] = {100, 150, 200, 250, 300}; 
   
   TH1D *h1_copy__3 = new TH1D("h1_copy__3","",4, xAxis11);
   h1_copy__3->SetBinContent(1,1);
   h1_copy__3->SetBinContent(2,1);
   h1_copy__3->SetBinContent(3,1);
   h1_copy__3->SetBinContent(4,1);
   h1_copy__3->SetBinError(1,0.4565234);
   h1_copy__3->SetBinError(2,0.2497174);
   h1_copy__3->SetBinError(3,0.4457885);
   h1_copy__3->SetBinError(4,0.409671);
   h1_copy__3->SetMinimum(0);
   h1_copy__3->SetMaximum(2);
   h1_copy__3->SetEntries(25.10473);
   h1_copy__3->SetDirectory(0);
   h1_copy__3->SetStats(0);
   h1_copy__3->SetFillColor(1);
   h1_copy__3->SetFillStyle(3001);
   h1_copy__3->SetLineColor(ci);
   h1_copy__3->SetLineWidth(2);
   h1_copy__3->SetMarkerColor(ci);
   h1_copy__3->GetXaxis()->SetTitle("#Sigma m_{T}^{#tau_{i}}");
   h1_copy__3->GetXaxis()->SetNdivisions(505);
   h1_copy__3->GetXaxis()->SetLabelFont(42);
   h1_copy__3->GetXaxis()->SetLabelSize(0);
   h1_copy__3->GetXaxis()->SetTitleSize(0.2);
   h1_copy__3->GetXaxis()->SetTickLength(0.09);
   h1_copy__3->GetXaxis()->SetTitleOffset(0.5);
   h1_copy__3->GetXaxis()->SetTitleFont(42);
   h1_copy__3->GetYaxis()->SetTitle("Data / MC");
   h1_copy__3->GetYaxis()->SetNdivisions(509);
   h1_copy__3->GetYaxis()->SetLabelFont(42);
   h1_copy__3->GetYaxis()->SetLabelSize(0.19);
   h1_copy__3->GetYaxis()->SetTitleSize(0.18);
   h1_copy__3->GetYaxis()->SetTitleOffset(0.36);
   h1_copy__3->GetYaxis()->SetTitleFont(42);
   h1_copy__3->GetZaxis()->SetLabelFont(42);
   h1_copy__3->GetZaxis()->SetLabelSize(0.035);
   h1_copy__3->GetZaxis()->SetTitleSize(0.035);
   h1_copy__3->GetZaxis()->SetTitleFont(42);
   h1_copy__3->Draw("sameaxis");
   MT2_ratio_ratiopad->Modified();
   MT2_ratioc_ratio->cd();
   MT2_ratioc_ratio->Modified();
   MT2_ratioc_ratio->cd();
   MT2_ratioc_ratio->SetSelected(MT2_ratioc_ratio);
   MT2_ratioc_ratio->ToggleToolBar();
}
